all:
  hosts:
    ubuntu_managed:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_user: root # The remote username to use when logging in via SSH. (ssh root@127.0.0.1 -p 2222.)
      ansible_ssh_private_key_file: ~/.ssh/ansible # Path to private SSH key on the control machine
